name: Build data archive

on:
  # Allows to call workflow from another workflow
  workflow_call:

jobs:
  build-data-archive:
    runs-on: ubuntu-latest

    # Grant `GITHUB_TOKEN` the necessary permissions.
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install just
        run: |
          wget -q -O - 'https://github.com/casey/just/releases/download/1.38.0/just-1.38.0-x86_64-unknown-linux-musl.tar.gz' | tar xvz just --to-stdout > /usr/local/bin/just
          chmod u+x /usr/local/bin/just

      - name: Fetch contributors
        run: just fetch-contributors

      - name: Write commit hash to file
        run: git rev-parse --short HEAD > data/commithash.txt

      - name: Write timestamp to file
        run: date --iso-8601=seconds --utc > data/timestamp.txt

      - name: Create archive
        run: tar cJf data.tar.xz data/

      - name: Upload archive as artifact
        uses: actions/upload-artifact@v4
        with:
          # The archive will additionally be wrapped in a ZIP archive.
          # This is a limitation of the `upload-artifact` action.
          name: lanpartydb-data.tar.xz.zip
          path: data.tar.xz

      - name: Configure Git user
        run: |
          git config user.name "workflow"
          git config user.email "workflow@invalid"

      - name: Create new branch
        run: git switch --orphan dist

      - name: Add, commit, and push files
        run: |
          git add data.tar.xz
          git commit -m 'Add data archive'
          git push --force origin dist
